language: haskell

os:
  - osx
  - linux

ghc:
  - "7.10"
  - 7.8

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

script: 
    - cabal install
    - /opt/ghc/$GHCVER/bin/unlambda examples/helloworld.un | grep "Hello, world\!"
